INSERT INTO `search`(`lname`, `unitName`) VALUES ('李红', '计算机学院');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('张卫红', '管理学院');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('刘小燕', '管理学院');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('李卫国', '东方大酒店');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('张小勇', '三洋公司');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('陈志军', '国际贸易公司');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('刘明', '机械学院');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('钱红', '机械学院');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('陈军军', '土木学院');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('张三', '20011321');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('李东', '20031322');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('张军', '20001015');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('陈俊', '20021821');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('刘洋', '20031821');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('高山', '研究生院');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('欧阳平', '研究生院');
INSERT INTO `search`(`lname`, `unitName`) VALUES ('刘倩', '研究生院');
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500010', '7-111-01342-5', '流通总库', '1', 15);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500011', '7-111-01342-5', '流通总库', '0', 7);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500012', '7-111-01342-5', '电气学院资料室', '0', 6);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500013', '7-111-01342-5', '教师阅览室', '2', 0);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500014', '7-111-06372-4', '机械学院资料室', '2', 0);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500015', '7-111-06372-4', '流通总库', '1', 15);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500016', '7-111-08571-X', '流通总库', '0', 15);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500017', '7-111-08571-X', '机械学院资料室', '0', 6);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500047', '7-111-06425-9', '流通总库', '0', 15);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500048', '7-111-06425-9', '流通总库', '3', 15);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500049', '7-111-06425-9', '流通总库', '1', 15);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500050', '7-111-06425-9', '管理学院资料室', '1', 6);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500051', '7-111-06425-9', '教师阅览室', '2', 0);
INSERT INTO `search`(`loanNo`, `lname`, `pwd`, `unitName`, `registerDate`, `classNo`, `email`, `amount`) VALUES ('G01000', '李红', '123456', '计算机学院', '2018-09-01 00:00:00', 4, 'LH@SOHU.COM', 0);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500048', '7-111-06425-9', '流通总库', '3', 15);
INSERT INTO `search`(`ISBN`, `bname`, `author`, `press`, `price`, `language`, `pages`) VALUES ('7-302-02284-4', '城市经济学', '谢文惠', '清华大学出版社', 36, '中文', 465);
INSERT INTO `search`(`ISBN`, `bname`, `author`, `press`, `price`, `language`, `pages`) VALUES ('7-302-04147-4', 'MBA入学考试英语大纲词汇手册', '何清', '清华大学出版社', 24, '中文', 224);
INSERT INTO `search`(`ISBN`, `bname`, `author`, `press`, `price`, `language`, `pages`) VALUES ('7-302-04384-1', '3D MAX 4使用速成', '孙海涛', '清华大学出版社', 50, '中文', 286);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500011', '7-111-01342-5', '流通总库', '0', 7);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500016', '7-111-08571-X', '流通总库', '0', 15);
INSERT INTO `search`(`bookNo`, `ISBN`, `location`, `bstatus`, `ctr_no`) VALUES ('A04500047', '7-111-06425-9', '流通总库', '0', 15);
INSERT INTO `search`(`ISBN`, `bname`, `author`, `press`, `price`, `language`, `pages`) VALUES ('7-04-006973-3', '高等数学', '陈庆华', '高等教育出版社', 46, '中文', 446);
INSERT INTO `search`(`ISBN`, `bname`, `author`, `press`, `price`, `language`, `pages`) VALUES ('7-111-01342-5', '数字电子技术', '刘全盛', '机械工业出版社', 44, '中文', 211);
INSERT INTO `search`(`ISBN`, `bname`, `author`, `press`, `price`, `language`, `pages`) VALUES ('7-111-07699-0', '热处理实用技术', '李泉华', '机械工业出版社', 48, '中文', 219);
INSERT INTO `search`(`ISBN`, `bname`, `author`, `press`, `price`, `language`, `pages`) VALUES ('7-301-01013-3', '数学与文化', '邓东皋', '北京大学出版社', 33, '中文', 397);
INSERT INTO `search`(`ISBN`, `bname`, `author`, `press`, `price`, `language`, `pages`) VALUES ('7-301-06033-5', '邓小平理论与当代中国政治学', '宁骚,关海庭', '北京大学出版社', 46, '中文', 412);
INSERT INTO `search`(`ISBN`, `bname`, `author`, `press`, `price`, `language`, `pages`) VALUES ('7-302-02284-4', '城市经济学', '谢文惠', '清华大学出版社', 36, '中文', 465);
INSERT INTO `search`(`ISBN`, `bname`, `author`, `press`, `price`, `language`, `pages`) VALUES ('7-5609-0873-X', '数据库系统基础', '冯玉才', '华中理工大学出版社', 36, '中文', 486);
INSERT INTO `search`(`ISBN`, `bname`, `author`, `press`, `price`, `language`, `pages`) VALUES ('7-80076-825-2', '法律基础知识', '易俊', '中国人事出版社', 30.8, '中文', 422);
INSERT INTO `search`(`loanNo`, `bookNo`, `borrowDate`, `returnDate`) VALUES ('A04500017\r\n', 'G01000\r\n', '2019-06-01 00:00:00', '2019-06-24 00:00:00');
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('3D MAX 4使用速成', '孙海涛', '清华大学出版社', 50);
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('市场营销学', '兰苓', '首都经济贸易大学出版社', 56);
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('PowerBuilder数据库开发技术', '陈桂友', '机械工业出版社', 58);
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('Access2002学习指导直导：数据库实例导航', '桂思强', '中国铁道出版社', 78);
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('数据库系统基础', '冯玉才', '华中理工大学出版社', 36);
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('PowerBuilder数据库开发技术', '陈桂友', '机械工业出版社', 58);
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('Access2002学习指导直导：数据库实例导航', '桂思强', '中国铁道出版社', 78);
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('数据库系统基础', '冯玉才', '华中理工大学出版社', 36);
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('Access2002学习指导直导：数据库实例导航', '桂思强', '中国铁道出版社', 78);
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('PowerBuilder数据库开发技术', '陈桂友', '机械工业出版社', 58);
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('数据库系统基础', '冯玉才', '华中理工大学出版社', 36);
INSERT INTO `search`(`ID`, `loanNo`, `bookNo`, `amount`, `reason`, `billdate`) VALUES (3, 'S02151', NULL, 100, '办证押金', '2019-06-01 00:00:00');
INSERT INTO `search`(`ID`, `loanNo`, `bookNo`, `amount`, `reason`, `billdate`) VALUES (1, 'S02152', NULL, 10, '办证费', '2019-05-05 00:00:00');
INSERT INTO `search`(`ID`, `loanNo`, `bookNo`, `amount`, `reason`, `billdate`) VALUES (2, 'S02152', NULL, 100, '办证押金', '2019-05-05 00:00:00');
INSERT INTO `search`(`ID`, `loanNo`, `bookNo`, `amount`, `reason`, `billdate`) VALUES (4, 'S02153', NULL, 100, '办证押金', '2018-06-02 00:00:00');
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('人力资源管理', 'Ivancevich,J.M.', '机械工业出版社', 150);
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('C++面向对象程序设计', '郑家瑜', '中国铁道出版社', 92);
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('Access2002学习指导直导：数据库实例导航', '桂思强', '中国铁道出版社', 78);
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('组织行为学', '龚敏', '上海财经大学出版社', 70);
INSERT INTO `search`(`bname`, `author`, `press`, `price`) VALUES ('微观经济学:第二版', '朱善利', '北京大学出版社', 64);
INSERT INTO `search`(`press`) VALUES ('高等教育出版社');
INSERT INTO `search`(`press`) VALUES ('机械工业出版社');
INSERT INTO `search`(`press`) VALUES ('中国铁道出版社');
INSERT INTO `search`(`press`) VALUES ('北京大学出版社');
INSERT INTO `search`(`press`) VALUES ('清华大学出版社');
INSERT INTO `search`(`press`) VALUES ('华中理工大学出版社');
INSERT INTO `search`(`press`) VALUES ('首都经济贸易大学出版社');
INSERT INTO `search`(`press`) VALUES ('中国人事出版社');
INSERT INTO `search`(`press`) VALUES ('上海财经大学出版社');
INSERT INTO `search`(`count(*)`) VALUES (17);
INSERT INTO `search`(`count( bstatus )`) VALUES (4);
INSERT INTO `search`(`sum( amount )`) VALUES (300);
INSERT INTO `search`(`max( price )`) VALUES (150);
INSERT INTO `search`(`min( price )`) VALUES (12.300000190734863);
INSERT INTO `search`(`press`) VALUES ('高等教育出版社');
INSERT INTO `search`(`press`) VALUES ('机械工业出版社');
INSERT INTO `search`(`press`) VALUES ('中国铁道出版社');
INSERT INTO `search`(`press`) VALUES ('北京大学出版社');
INSERT INTO `search`(`press`) VALUES ('清华大学出版社');
INSERT INTO `search`(`press`) VALUES ('华中理工大学出版社');
INSERT INTO `search`(`press`) VALUES ('首都经济贸易大学出版社');
INSERT INTO `search`(`press`) VALUES ('中国人事出版社');
INSERT INTO `search`(`press`) VALUES ('上海财经大学出版社');
INSERT INTO `search`(`count(*)`) VALUES (4);
INSERT INTO `search`(`count(*)`) VALUES (6);
INSERT INTO `search`(`count(*)`) VALUES (2);
INSERT INTO `search`(`count(*)`) VALUES (5);
INSERT INTO `search`(`count(*)`) VALUES (3);
INSERT INTO `search`(`count(*)`) VALUES (1);
INSERT INTO `search`(`count(*)`) VALUES (1);
INSERT INTO `search`(`count(*)`) VALUES (1);
INSERT INTO `search`(`count(*)`) VALUES (1);
INSERT INTO `search`(`amount`, `reason`) VALUES (100, '办证押金');
INSERT INTO `search`(`amount`, `reason`) VALUES (100, '办证押金');
INSERT INTO `search`(`lname`, `unitName`, `bookNo`, `loanNo`, `borrowDate`) VALUES ('陈军军', '土木学院', NULL, NULL, NULL);
INSERT INTO `search`(`lname`, `unitName`, `bookNo`, `loanNo`, `borrowDate`) VALUES ('刘明', '机械学院', NULL, NULL, NULL);
INSERT INTO `search`(`lname`, `unitName`, `bookNo`, `loanNo`, `borrowDate`) VALUES ('钱红', '机械学院', NULL, NULL, NULL);
INSERT INTO `search`(`lname`, `unitName`, `bookNo`, `loanNo`, `borrowDate`) VALUES ('张卫红', '管理学院', NULL, NULL, NULL);
INSERT INTO `search`(`lname`, `unitName`, `bookNo`, `loanNo`, `borrowDate`) VALUES ('李红', '计算机学院', NULL, NULL, NULL);
INSERT INTO `search`(`loanNo`, `lname`) VALUES ('S06102', '刘明');
INSERT INTO `search`(`loanNo`, `lname`) VALUES ('S06103', '钱红');
