SELECT lname, unitName FROM users;
SELECT * FROM bookinfo;
SELECT * FROM users WHERE unitName = '计算机学院';
SELECT * FROM books WHERE bstatus = 3;
SELECT  bookNo, loanNo FROM loan WHERE DATEDIFF(NOW(),borrowDate) > 60; 
SELECT bname, author, price FROM bookinfo WHERE press = '清华大学出版社';
SELECT * FROM books WHERE (location = '流通总库'||'计算机学院资料室') && bstatus = '0';
SELECT * FROM bookinfo WHERE price BETWEEN 30 AND 50;
SELECT * FROM loanhist WHERE YEAR(borrowDate) = '2019';
SELECT bname, author, press, price FROM bookinfo WHERE author in('兰苓','孙海涛','刘明');
SELECT bname, author, press, price FROM bookinfo WHERE bname LIKE '%数据库%';
SELECT bname, author, press, price * 1.5 AS price FROM bookinfo WHERE bname LIKE '%数据库%';
SELECT bname, author, press, price * 1.5 AS price FROM bookinfo WHERE bname LIKE '%数据库%' ORDER BY bname;
SELECT * FROM money ORDER BY billdate DESC,amount;
SELECT bname, author, press, price FROM bookinfo ORDER BY price DESC LIMIT 5;
SELECT bookinfo.press,COUNT(*) FROM books,bookinfo WHERE books.ISBN=bookinfo.ISBN GROUP BY press;
SELECT COUNT(*) FROM users;
SELECT COUNT(DISTINCT loanNo) FROM loan;
SELECT SUM(amount) FROM money WHERE reason = '办证押金';
select AVG(DATEDIFF(returnDate,borrowDate)) from LoanHist	GROUP by loanNo;
SELECT MAX(price), MIN(price) FROM bookinfo;
SELECT press, COUNT(*) FROM bookinfo GROUP BY press;
SELECT bname,COUNT(*) FROM books, bookinfo WHERE bookinfo.ISBN = books.ISBN GROUP BY bookinfo.ISBN;
SELECT bname,COUNT(*) FROM books, bookinfo WHERE bookinfo.ISBN = books.ISBN GROUP BY bookinfo.ISBN HAVING COUNT(*) > 3;
SELECT reason, SUM(amount) FROM money WHERE billdate BETWEEN '2019-01-01 00:00:00' and '2019-12-31 00:00:00' group by reason HAVING SUM(amount) > 50;